# Generated by Django 4.1.3 on 2022-11-08 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                ("image", models.ImageField(upload_to="about_company/")),
                ("description", models.TextField()),
                (
                    "video",
                    models.FileField(
                        null=True,
                        upload_to="videos_uploaded/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
