# Generated by Django 4.1.3 on 2022-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Prosess"),
                            (2, "Canceled"),
                            (3, "Finished"),
                        ],
                        default=0,
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("from_i", models.CharField(max_length=50)),
                ("to_i", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=12)),
            ],
        ),
    ]
