# Generated by Django 4.1.3 on 2022-11-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                ("image", models.ImageField(upload_to="objects/")),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("price", models.CharField(default=0, max_length=20)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
