# Generated by Django 4.1.3 on 2022-11-09 06:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objects",
            old_name="date_create",
            new_name="date_created",
        ),
        migrations.RemoveField(
            model_name="objects",
            name="image",
        ),
        migrations.AlterField(
            model_name="objects",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="objects.category",
            ),
        ),
        migrations.AlterField(
            model_name="objects",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name="ObjectImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="CarsImages")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "object",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_images",
                        to="objects.objects",
                    ),
                ),
            ],
        ),
    ]
