# Generated by Django 4.1.3 on 2022-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0002_rename_date_create_objects_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objects",
            name="siz",
        ),
        migrations.AddField(
            model_name="objects",
            name="size",
            field=models.FloatField(default=0),
        ),
    ]
