# Generated by Django 4.1.3 on 2022-11-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0003_remove_objects_siz_objects_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tonna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
